//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySchedule.EntityDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public int LINK { get; set; }
        public int F_group { get; set; }
        public int F_days { get; set; }
        public int F_timetable { get; set; }
        public Nullable<int> F_teacher { get; set; }
        public int F_typeweek { get; set; }
        public Nullable<int> F_subgroups { get; set; }
        public string subject { get; set; }
        public string audience { get; set; }
    
        public virtual Days Days { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual SubGroups SubGroups { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual Timetables Timetables { get; set; }
        public virtual TypeWeek TypeWeek { get; set; }
    }
}
